In [17]:
import numpy as np
import pandas as pd

In [18]:
df = pd.read_csv('../../data/Week1_GA_dataset.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               10000 non-null  str
 1   Year               10000 non-null  int64
 2   Locality           8747 non-null   str
 3   Estimated Value    8757 non-null   float64
 4   Sale Price         10000 non-null  float64
 5   Property           10000 non-null  str
 6   Residential        10000 non-null  str
 7   num_rooms          10000 non-null  int64
 8   num_bathrooms      10000 non-null  int64
 9   carpet_area        8771 non-null   float64
 10  property_tax_rate  10000 non-null  float64
 11  Face               10000 non-null  str
dtypes: float64(4), int64(3), str(5)
memory usage: 937.6 KB

In [5]:
df.head(5)

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East

In [9]:
(df == '?').sum().sum()

np.int64(1823)

In [13]:
df.shape

(10000, 12)

In [21]:
df.iloc[692,0]

'2009-11-16'

In [14]:
df.head(692)

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East
...,...,...,...,...,...,...,...,...,...,...,...,...
687,2009-11-14,2009,Bridgeport,57120.0,85000.0,Single Family,Detached House,3,1,1045.0,1.025953,South
688,2009-11-16,2009,Bridgeport,114240.0,250000.0,Single Family,Detached House,3,1,980.0,1.025953,East
689,2009-11-16,2009,Norwalk,446530.0,977000.0,Single Family,Detached House,3,1,903.0,1.025953,West
690,2009-11-16,2009,Norwalk,344050.0,725000.0,Single Family,Detached House,3,3,977.0,1.025953,West
691,2009-11-16,2009,Bridgeport,81900.0,260000.0,Single Family,Detached House,3,3,1053.0,1.025953,East

In [15]:
df.head(546)

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East
...,...,...,...,...,...,...,...,...,...,...,...,...
541,2009-08-16,2009,Bridgeport,119980.0,320000.0,Single Family,Detached House,3,1,NaN,1.025953,South
542,2009-08-16,2009,Norwalk,256842.0,687500.0,Single Family,Detached House,3,1,960.0,1.025953,East
543,2009-08-17,2009,Waterbury,65030.0,145000.0,Two Family,Duplex,4,2,NaN,1.025953,East
544,2009-08-17,2009,Fairfield,912870.0,1242500.0,?,Detached House,3,3,939.0,1.025953,East
545,2009-08-17,2009,Fairfield,387660.0,499500.0,?,Detached House,3,1,941.0,1.025953,East

In [20]:
df.iloc[546,7]

np.int64(3)

In [24]:
df['Locality'].nunique

<bound method IndexOpsMixin.nunique of 0        Waterbury
1       Bridgeport
2        Waterbury
3       Bridgeport
4       Bridgeport
           ...
9995    Bridgeport
9996    Bridgeport
9997     Waterbury
9998           NaN
9999       Norwalk
Name: Locality, Length: 10000, dtype: str>

In [25]:
df.replace('?', np.nan, inplace=True)
df.columns[df.isna().any()].tolist()

['Locality', 'Estimated Value', 'Property', 'carpet_area']

In [ ]:
##.idxmax()  Returns the column name with the highest count.
df.isna().sum().idxmax()

'Property'

In [31]:
df_clean = df.replace('?', np.nan)

df_clean = df_clean.dropna(thresh=10)

df_clean.shape[0]

9917

In [32]:
df_clean = df_clean[df_clean.isna().sum(axis=1) <= 2]
len(df_clean)

9917

In [33]:
df_clean = df_clean.dropna()

df_clean.shape[0]

5449

In [38]:
df.iloc[0:999:2]
df.iloc[0,3]

np.float64(111440.0)

In [48]:
even_df = df.iloc[::2]
even_df.iloc[332,3]

np.float64(256200.0)

In [52]:
odd_df= df.iloc[1::2]
odd_df.iloc[332,3]

np.float64(352940.0)

In [57]:
odd_df= df.iloc[:,1::2]
odd_df.iloc[100,5]

'West'

In [58]:
even_df=df.iloc[:,::2]
even_df.iloc[255,3]

'Detached House'

In [ ]:
d

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
9994,2022-09-30,2022,NaN,155550.0,215000.0,Three Family,Triplex,6,5,2114.0,1.003979,North
9995,2022-09-30,2022,Bridgeport,153660.0,322000.0,NaN,Detached House,3,3,917.0,1.003979,North
9996,2022-09-30,2022,Bridgeport,109820.0,340000.0,NaN,Duplex,4,4,1416.0,1.003979,North
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South
9998,2022-09-30,2022,NaN,216420.0,415000.0,Single Family,Detached House,3,3,1014.0,1.003979,North
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East

In [65]:
df[(df['num_rooms']== 3) & (df['num_bathrooms']==3)].shape[0]

2730

In [66]:
df[(df['num_rooms']== 3) | (df['num_bathrooms']==3)].shape[0]

8591

In [71]:
df[(df['Year']==2022) & (df['Locality']== 'Greenwich') & (df['num_rooms']==3) & ((df['Face']== 'North') | (df['Face']== 'East'))].shape[0]

42

In [72]:
df['Date']  = pd.to_datetime(df['Date'])
df[df['Date'].dt.month == 8].shape[0]

1050

In [77]:
df.groupby('Locality')['Sale Price'].mean().sort_values(ascending=False)

Locality
Greenwich        2.270224e+06
Fairfield        7.277225e+05
Stamford         6.305313e+05
Norwalk          5.590959e+05
West Hartford    3.385472e+05
Bridgeport       1.740953e+05
Waterbury        1.062152e+05
Name: Sale Price, dtype: float64